name: medguard
description: "medicine_reminder_app"
publish_to: 'Aarthav Technology' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0' # Updated to a more standard constraint

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For internationalization
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  collection: ^1.19.0 # Matched to a stable version
  logger: ^2.3.0

  # Firebase Packages
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.1
  firebase_crashlytics: ^4.0.1
  
  # UI & Feature Packages
  google_fonts: ^6.2.1
  mobile_scanner: ^5.1.2 # Updated to latest stable patch
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to a stable version

  # Code Generators and Tooling
  flutter_gen_runner: ^5.5.0 # Correct way to add flutter_gen
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  # Declare your assets folder
  assets:
    - assets/

# --- CONFIGURATION FOR GENERATORS ---

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0D47A1"
  image: assets/icon.png
  android_12:
    color: "#0D47A1"
    image: assets/icon.png